INSERT INTO roles (id,name,description) VALUES (1,'Super Admin','Acceso total'),(2,'Administrador','Gestiona leads, asignaciones y exportaciones'),(3,'Ejecutivo','Gestiona leads asignados'),(4,'Visualizador','Solo lectura');
INSERT INTO users (name,email,password_hash,role_id,status,created_at,updated_at) VALUES ('Administrador Crecer','admin@creceracredita.cl','$2y$12$7Dh4VRw5bSAwZHAAXfPlyubezPZ62LZ/cqVZfh/7/JR16I5s7b6C.',1,'active',NOW(),NOW());
INSERT INTO assessment_questions (module_name,question_text,weight,sort_order,status) VALUES
('Cumplimiento Laboral','¿Todos los trabajadores cuentan con contrato firmado?',30,1,1),('Cumplimiento Laboral','¿Los anexos de contrato se encuentran actualizados?',30,2,1),('Cumplimiento Laboral','¿La empresa mantiene registro de asistencia actualizado?',30,3,1),('Cumplimiento Laboral','¿Las liquidaciones de sueldo se encuentran disponibles y respaldadas?',30,4,1),('Cumplimiento Laboral','¿Existe control documental de la información laboral?',30,5,1),
('Cumplimiento Previsional','¿Las cotizaciones previsionales se pagan oportunamente?',25,6,1),('Cumplimiento Previsional','¿La empresa dispone de respaldo de pagos previsionales?',25,7,1),('Cumplimiento Previsional','¿Cuenta con certificados previsionales vigentes?',25,8,1),('Cumplimiento Previsional','¿Existe control periódico de obligaciones previsionales?',25,9,1),
('Seguridad y Salud Ocupacional','¿Los trabajadores cuentan con ODI?',25,10,1),('Seguridad y Salud Ocupacional','¿Se realizan inducciones formales?',25,11,1),('Seguridad y Salud Ocupacional','¿Existe registro de entrega de EPP?',25,12,1),('Seguridad y Salud Ocupacional','¿Los exámenes ocupacionales se encuentran vigentes?',25,13,1),('Seguridad y Salud Ocupacional','¿La empresa mantiene registros de capacitación?',25,14,1),
('Control Documental','¿La documentación requerida se encuentra vigente?',10,15,1),('Control Documental','¿Existe seguimiento de vencimientos?',10,16,1),('Control Documental','¿Hay responsables asignados para el control documental?',10,17,1),
('Gestión de Contratistas','¿La empresa cuenta con procedimientos de gestión de contratistas?',10,18,1),('Gestión de Contratistas','¿Se realizan revisiones periódicas de cumplimiento?',10,19,1),('Gestión de Contratistas','¿Existe seguimiento de observaciones y hallazgos?',10,20,1);
INSERT INTO settings(setting_key,setting_value) VALUES ('brand_primary','#062B5F'),('brand_green','#0B8F63'),('brand_mustard','#D6A51A');
