<?php
namespace App\Models;
class Lead extends Model { public array $statuses=['Nuevo','Contactado','En seguimiento','Reunión agendada','Propuesta enviada','Cerrado ganado','Cerrado perdido'];
 public function stats(){
  $base=['total'=>$this->db->query('SELECT COUNT(*) c FROM clients')->fetch()['c']??0,'evaluations'=>$this->db->query('SELECT COUNT(*) c FROM assessment_results')->fetch()['c']??0,'avg'=>$this->db->query('SELECT ROUND(AVG(risk_score),1) c FROM clients')->fetch()['c']??0,'risk'=>$this->db->query('SELECT risk_level,COUNT(*) total FROM clients GROUP BY risk_level')->fetchAll(),'industry'=>$this->db->query('SELECT industry,COUNT(*) total FROM clients GROUP BY industry ORDER BY total DESC LIMIT 8')->fetchAll()];
  $modules=$this->db->query("SELECT 'Cumplimiento Laboral' module_name, ROUND(AVG(labor_score),1) avg_score FROM assessment_results UNION ALL SELECT 'Cumplimiento Previsional', ROUND(AVG(pension_score),1) FROM assessment_results UNION ALL SELECT 'Seguridad y Salud Ocupacional', ROUND(AVG(safety_score),1) FROM assessment_results UNION ALL SELECT 'Control Documental', ROUND(AVG(document_score),1) FROM assessment_results UNION ALL SELECT 'Gestión de Contratistas', ROUND(AVG(contractor_score),1) FROM assessment_results")->fetchAll();
  $gaps=$this->db->query("SELECT q.module_name,q.question_text,COUNT(*) total_answers,SUM(a.answer_value=0) no_count,SUM(a.answer_value=5) partial_count,ROUND(AVG(a.answer_value)*10,1) compliance_score FROM assessment_answers a JOIN assessment_questions q ON q.id=a.question_id GROUP BY q.id,q.module_name,q.question_text HAVING total_answers > 0 ORDER BY compliance_score ASC, no_count DESC LIMIT 5")->fetchAll();
  $funnel=$this->db->query('SELECT risk_status,COUNT(*) total FROM clients GROUP BY risk_status ORDER BY total DESC')->fetchAll();
  $answerSummary=$this->db->query("SELECT q.module_name,COUNT(*) total_answers,SUM(a.answer_value=10) yes_count,SUM(a.answer_value=5) partial_count,SUM(a.answer_value=0) no_count,ROUND(AVG(a.answer_value)*10,1) compliance_score FROM assessment_answers a JOIN assessment_questions q ON q.id=a.question_id GROUP BY q.module_name ORDER BY compliance_score ASC")->fetchAll();
  $questionStats=$this->db->query("SELECT q.module_name,q.question_text,COUNT(*) total_answers,SUM(a.answer_value=10) yes_count,SUM(a.answer_value=5) partial_count,SUM(a.answer_value=0) no_count,ROUND(AVG(a.answer_value)*10,1) compliance_score FROM assessment_answers a JOIN assessment_questions q ON q.id=a.question_id GROUP BY q.id,q.module_name,q.question_text HAVING total_answers > 0 ORDER BY q.sort_order LIMIT 12")->fetchAll();
  $base['modules']=$modules; $base['gaps']=$gaps; $base['funnel']=$funnel; $base['answer_summary']=$answerSummary; $base['question_stats']=$questionStats;
  $base['high_risk']=$this->db->query("SELECT COUNT(*) c FROM clients WHERE risk_level='Riesgo alto'")->fetch()['c']??0;
  $base['pending']=$this->db->query("SELECT COUNT(*) c FROM clients WHERE risk_status IN ('Nuevo','Contactado','En seguimiento')")->fetch()['c']??0;
  return $base;
 }
 public function latest($limit=8){$s=$this->db->prepare('SELECT c.*,u.name assigned_name FROM clients c LEFT JOIN users u ON u.id=c.assigned_user_id ORDER BY c.created_at DESC LIMIT ?');$s->bindValue(1,$limit,\PDO::PARAM_INT);$s->execute();return $s->fetchAll();}
 public function search($q=[]){$w=[];$p=[]; if(!empty($q['search'])){$w[]='(company_name LIKE ? OR company_rut LIKE ? OR contact_name LIKE ? OR email LIKE ? OR city LIKE ?)';$term='%'.$q['search'].'%';$p=array_merge($p,array_fill(0,5,$term));} foreach(['industry','risk_level','assigned_user_id'] as $f){if(!empty($q[$f])){$w[]="c.$f=?";$p[]=$q[$f];}} if(!empty($q['date_from'])){$w[]='DATE(c.created_at)>=?';$p[]=$q['date_from'];} if(!empty($q['date_to'])){$w[]='DATE(c.created_at)<=?';$p[]=$q['date_to'];} $sql='SELECT c.*,u.name assigned_name FROM clients c LEFT JOIN users u ON u.id=c.assigned_user_id'.($w?' WHERE '.implode(' AND ',$w):'').' ORDER BY c.created_at DESC LIMIT 100';$s=$this->db->prepare($sql);$s->execute($p);return $s->fetchAll();}
 public function find($id){$s=$this->db->prepare('SELECT c.*,u.name assigned_name FROM clients c LEFT JOIN users u ON u.id=c.assigned_user_id WHERE c.id=?');$s->execute([$id]);return $s->fetch();}
 public function result($id){$s=$this->db->prepare('SELECT * FROM assessment_results WHERE client_id=? ORDER BY id DESC LIMIT 1');$s->execute([$id]);return $s->fetch();}
 public function answers($id){$s=$this->db->prepare('SELECT a.*,q.question_text FROM assessment_answers a JOIN assessment_questions q ON q.id=a.question_id WHERE a.client_id=? ORDER BY q.sort_order');$s->execute([$id]);return $s->fetchAll();}
 public function logs($id){$s=$this->db->prepare('SELECT l.*,u.name user_name FROM activity_logs l LEFT JOIN users u ON u.id=l.user_id WHERE entity_type="client" AND entity_id=? ORDER BY created_at DESC');$s->execute([$id]);return $s->fetchAll();}
 public function update($id,$d){$s=$this->db->prepare('UPDATE clients SET notes=?,assigned_user_id=?,risk_status=?,updated_at=NOW() WHERE id=?');return $s->execute([$d['notes'],$d['assigned_user_id']?:null,$d['risk_status'],$id]);}
}
